# Generated by Django 5.0.3 on 2024-03-30 08:34

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Qaror muallifi')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
            ],
        ),
        migrations.CreateModel(
            name='CheckFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=main.models.upload_file_check, verbose_name='File')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
            ],
        ),
        migrations.CreateModel(
            name='ControlCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nazorat kartasi turi')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
            ],
        ),
        migrations.CreateModel(
            name='ControlFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=main.models.upload_file_control, verbose_name='')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hujjat turi')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Guruhi')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Muhbir')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
            ],
        ),
        migrations.CreateModel(
            name='TypeSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Yechim turi')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Markaz')),
                ('short', models.CharField(blank=True, max_length=255, null=True, verbose_name='Short Name')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(verbose_name="Ro'yhatga olingan sana")),
                ('registration_number', models.CharField(max_length=150, verbose_name="Ro'yhatga olingan raqam")),
                ('document_number', models.CharField(max_length=150, verbose_name='Hujjat raqami')),
                ('document_date', models.DateField(verbose_name='Hujjat sanasi')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Xulosa')),
                ('control', models.BooleanField(default=False, verbose_name='Boshqaruv')),
                ('resolution', models.TextField(blank=True, null=True, verbose_name='Rezolutsiya')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('auth_resolution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.authorresolution', verbose_name='Qaror muallifi')),
                ('control_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.controlcard', verbose_name='Nazorat Kartasi')),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.documenttype', verbose_name='Hujjat turi')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.group', verbose_name='Guruh')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.reporter', verbose_name='Muxbir')),
                ('type_solution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.typesolution', verbose_name='Yechim turi')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifetime', models.DateField(verbose_name='Muddat')),
                ('control', models.BooleanField(default=False, verbose_name='Tasdiqlash')),
                ('centers', models.ManyToManyField(to='main.center', verbose_name='Markazlar')),
                ('check_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.checkfile', verbose_name="So'rov file")),
                ('control_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.controlfile', verbose_name='Javob file')),
                ('letter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.letter', verbose_name='Xat')),
            ],
        ),
    ]
